server:
  port: 3000

spring:
  application:
    name: orderservice

  data:
    mongodb:
      database: admin
      uri: ${MONGO_DB_URI:mongodb://admin:123456@localhost:27017}

  kafka:
    bootstrap-service: ${KAFKA_BROKER:localhost:9092}
    topic:
        start-saga: start-saga
        notify-ending: notify-ending
    consumer:
      group-id: order-group
      auto-offset-reset: latest

logging:
  level:
    org:
      apache:
        kafka: OFF

